//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Nr_Sali { get; set; }
        public string Rodzaj_sali { get; set; }
        public int Ilość_miejsc { get; set; }
        public int Rodzaj_krzeseł { get; set; }
        public int Rodzaj_ławek { get; set; }
        public string Projektor { get; set; }
    
        public virtual Krzesła Krzesła { get; set; }
        public virtual Ławki Ławki { get; set; }
    }
}
